language: node_js  #设置语言

node_js: stable  #设置相应的版本

cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

install:
  - npm install  #安装hexo及插件

script:
  - hexo clean  #清除
  - hexo g  #生成

after_script:
  - cd ./public
  - git init
  - git config --global user.name "qiyu Tien"  #修改name
  - git config --global user.email "tianqiyu119@126.com"  #修改email
  - git add ./
  - git commit -m "update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master

branches:
  only:
    - hexo-source
env:
  global:
    - GH_REF: github.com/tianqiyu119/tianqiyu119.github.io.git
